### ISSUE TITLE
'Our History' text is not aligned with image proportionally

### ISSUE THREAD

**Issue by AmannaWong** [anishakb/AdagioWine#23]
Configuration:

Devices:
Mac OS, Windows

Browsers:
Chrome, Firefox, Safari

Setup Tasks & Data:
Visit the website [https://adagio.anishabhalla.com]

Steps:

1) Launch website
2) Select about page in navigation
3) Resize browser window 

Expected Result:

User should be able to see the about page and be able to comfortably read the Our History section, while maintaining its pleasant design.

Actual Result:

User sees stretched out text that is not in line with section, and there are parts of the text that go past the image 

![image](https://user-images.githubusercontent.com/107274225/231051298-6b832be0-b301-43f8-bda5-6dbd0ee543fc.png)

**Comment by anishakb** [comment]
The text space has ben adjusted on the recent commit.
