### ISSUE TITLE
Website broken at screen size smaller than 575px on About Page

### ISSUE THREAD

**Issue by AmannaWong** [anishakb/AdagioWine#24]
Configuration:

Devices:
Mac OS, Windows

Browsers:
Chrome, Firefox, Safari

Setup Tasks & Data:
Visit the website [https://adagio.anishabhalla.com]

Steps:

1) Launch the website on browser.
2) Right click the website and select inspect element
3) Change the screen size width to any number below 575

Expected Result:

Website should look like the designed wireframes, as well as stay consistent with the other breakpoints

Actual Result:

The site is shrunk and not usable. Elements are also missing from the design

**Comment by anishakb** [comment]
Issue resolved by addition of about.css
